AulaDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('music_app.urls'))
]

music_app/urls.py
from django.urls import path
from music_app.views import (
    AlbumListView, AlbumDetailView,
    CreateAlbumView, CreateMusicView,
    AlbumUpdateView, AlbumDeleteView
)

app_name = "music_app"

urlpatterns = [
    path('', AlbumListView.as_view()),
    path('album/<pk>', AlbumDetailView.as_view(), name="album_detail"),
    path('create_album/', CreateAlbumView.as_view(), name="create_album"),
    path('update_album/<pk>', AlbumUpdateView.as_view(), name="update_album"),
    path('delete_album/<pk>', AlbumDeleteView.as_view(), name="delete_album"),
    path('create_music/', CreateMusicView.as_view(), name="create_music"),
]

music_app/models.py
from django.db import models


class ModificationsLog(models.Model):
    updated_at = models.DateTimeField("Atualizado em", auto_now_add=True)
    created_at = models.DateTimeField("Criado em", auto_now=True)

    class Meta:
        abstract = True


class Album(ModificationsLog):
    title = models.CharField("Título do Álbum", max_length=256)
    author = models.CharField("Nome do Autor/Banda", max_length=256)
    style = models.CharField("Estilo da Música", max_length=256)
    track_numbers = models.PositiveIntegerField("Número de Músicas")

    class Meta:
        verbose_name = 'Álbum'
        verbose_name_plural = 'Álbuns'

    def __str__(self):
        return f'{self.title} / {self.author}'


class Music(ModificationsLog):
    title = models.CharField("Título da Música", max_length=256)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    duration = models.CharField("Duração", max_length=256)

    class Meta:
        verbose_name = 'Música'
        verbose_name_plural = 'Músicas'

    def __str__(self):
        return f'{self.title} / {self.album}'

music_app/forms.py
from django import forms
from django.forms import ModelForm

from .models import Album, Music


class AlbumForm(ModelForm):

    class Meta:
        model = Album
        fields = '__all__'

        widgets = {
            'title': forms.TextInput(attrs={
                'placeholder': 'Título do álbum', 'class': 'form-control',
            }),
            'author': forms.TextInput(attrs={
                'placeholder': 'Autor do álbum', 'class': 'form-control',
            }),
            'style': forms.TextInput(attrs={
                'placeholder': 'Estilo do álbum', 'class': 'form-control',
            }),
            'track_numbers': forms.TextInput(attrs={
                'placeholder': 'Número de músicas do álbum',
                'class': 'form-control',
            }),
        }


class MusicForm(ModelForm):

    class Meta:
        model = Music
        fields = '__all__'

        widgets = {
            'title': forms.TextInput(attrs={
                'placeholder': 'Título da música', 'class': 'form-control',
            }),
            'album': forms.Select(attrs={
                'class': 'form-control',
            }),
            'duration': forms.TextInput(attrs={
                'placeholder': 'Duração da música', 'class': 'form-control',
            }),
        }

music_app/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from .models import Album, Music
from .forms import AlbumForm, MusicForm


class AlbumListView(ListView):
    model = Album
    context_object_name = 'albums'
    template_name = 'albums_list.html'


class AlbumDetailView(DetailView):
    model = Album
    context_object_name = 'album'
    template_name = 'album_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['album_musics'] = Music.objects.filter(album=self.kwargs['pk'])
        context['album_data'] = [100, 10, 5, 2, 20, 30, 45]
        return context


class AlbumUpdateView(UpdateView):
    form_class = AlbumForm
    model = Album
    template_name = 'create_update_album.html'
    success_url = '/'


class AlbumDeleteView(DeleteView):
    model = Album
    context_object_name = 'album'
    success_url = '/'
    template_name = 'album_confirm_delete.html'


class CreateAlbumView(CreateView):
    form_class = AlbumForm
    template_name = 'create_update_album.html'
    success_url = '/'


class CreateMusicView(CreateView):
    form_class = MusicForm
    template_name = 'create_music.html'
    success_url = '/'

music_app/templates/album_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h1>Deletar Álbum</h1>
    <hr>
    <p>Você tem certeza disso "{{ album }}"?</p>
    <input class="btn btn-danger" type="submit" value="Deletar!">
</form>
{% endblock %}

music_app/templates/album_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>Títulos das músicas ({{ album.title }}/{{ album.author }})</h1>
    <hr>
    <ul>
    {% for music in album_musics %}
        <li>
            Música: {{ music.title }} <br/>
            Duração: {{ music.duration }}
        </li>
    {% endfor %}
    <p>Número de músicas: {{ album_musics|length }}</p>
    </ul>
    <a class="btn btn-primary mr-3" href="{% url 'music_app:update_album' album.pk %}">Atualizar Álbum</a>
    <a class="btn btn-danger mr-3" href="{% url 'music_app:delete_album' album.pk %}">Deletar Álbum</a>
    <a href="/">Retornar aos Álbuns</a>

    <canvas id="myChart"></canvas>

{% endblock %}

{% block custom_script %}
    <script>
    var ctx = document.getElementById('myChart').getContext('2d');
    var chart = new Chart(ctx, {
        // The type of chart we want to create
        type: 'line',

        // The data for our dataset
        data: {
            labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
            datasets: [{
                label: 'My First dataset',
                backgroundColor: 'rgb(255, 99, 132)',
                borderColor: 'rgb(255, 99, 132)',
                data: {{ album_data }}
            }]
        },

        // Configuration options go here
        options: {}
    });
    </script>
{% endblock%}

music_app/templates/albums_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Álbuns existentes</h1>
    <hr>
    <ul>
    {% for album in albums %}
        <li>
            <a href="{% url 'music_app:album_detail' album.pk %}">{{ album.title }}</a>
        </li>
    {% endfor %}
    <p>Número de álbums: {{ albums|length }}</p>
    </ul>
    <a href="{% url 'music_app:create_album' %}" class="btn btn-dark float-right">Criar Novo Álbum</a>
    <a href="{% url 'music_app:create_music' %}" class="btn btn-dark float-right mr-3">Criar Nova Música</a>
{% endblock %}

music_app/templates/base.html
<html>
    {% load static %}
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'my_style.css' %}">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="/">Tubanharon</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Álbuns <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Dropdown
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
        <div class="container mt-5">
            <div class="jumbotron">
                {% block content %}
                {% endblock %}
            </div>
        </div>
        
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js" integrity="sha256-xKeoJ50pzbUGkpQxDYHD7o7hxe0LaOGeguUidbq6vis=" crossorigin="anonymous"></script>

    {% block custom_script %}
    {% endblock%}
    </body>
</html>

music_app/templates/create_music.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    <h1>Formulário para criação de nova música</h1>
    <hr>
    <div class="form-group">
        <label for="id_title">{{ form.title.label }}</label>
        {{ form.title }}
    </div>
    <div class="form-group">
        <label for="id_author">{{ form.album.label }}</label>
        {{ form.album }}
    </div>
    <div class="form-group">
        <label for="id_style">{{ form.duration.label }}</label>
        {{ form.duration }}
    </div>
    <button type="submit" class="btn btn-primary">Enviar</button>
</form>
{% endblock %}

music_app/templates/create_update_album.html
{% extends 'base.html' %}

{% block content %}
    <h1>Formulário para criação de novo álbum</h1>
    <hr>
    {% if error %}
    <div class="alert alert-danger" role="alert">
      {{ error }}
    </div>
    {% endif %}
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_title">{{ form.title.label }}</label>
            {{ form.title }}
        </div>
        <div class="form-group">
            <label for="id_author">{{ form.author.label }}</label>
            {{ form.author }}
        </div>
        <div class="form-group">
            <label for="id_style">{{ form.style.label }}</label>
            {{ form.style }}
        </div>
        <div class="form-group">
            <label for="id_track_numbers">{{ form.track_numbers.label }}</label>
            {{ form.track_numbers }}
        </div>
        <button type="submit" class="btn btn-primary">Enviar</button>
    </form>
{% endblock %}